// Generated by scripts/make-icons.mjs — do not edit by hand.
export interface TrayIconEntry {
  readonly size: number;
  readonly base64: string;
}

export const trayIcons: readonly TrayIconEntry[] = [{"size":16,"base64":"iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAZklEQVR42mOosXrLUGP11qHG6u1/EjFIDwO5muGGMFCgGYyxGrBv7jfyDZib/ek/CNw79xvMJssFII0gA0CAkCF4wwBmCD4vEQxEkGaYl+hvANleoCgQqRKNFCUkcpIyxZmJouwMAKB6sef8GxFsAAAAAElFTkSuQmCC"},{"size":32,"base64":"iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAuElEQVR42mOosXrLgIYbaqze/qcRbkC3D5njQEOL0bEDugPoaTmKI2AO+D9AmIHWcU4wTQyk78F4aDhgbvan/yBw79xvMJvuDtg399t/ZEBNRxAdBSDfIwOQo+ieBtAdAeLTPRHC0gOyIyiJErJyAbojKEkXFGVDaqQLissBStMFVQoibOli5DhgQKNgwBLhgGbDAS2IBrQoHtDKaMCr4wFvkAz7NuGAN8sHvGMyKLpmA945HbDuOQCONMDbNM2zlgAAAABJRU5ErkJggg=="}];
